# [Usage]
#
# $ gem install gem_comet
# $ gem_comet release {version number, like as "1.2.3"}

version: 1

release:
  base_branch: master
  release_branch: production
  version_file_path: lib/my_api_client/version.rb
