require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'my_api_client.gemspec'
    - 'lib/my_api_client/rspec/matchers/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/DescribeClass:
  Exclude:
    - 'spec/lib/my_api_client/rspec/matchers/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Exclude:
    - 'spec/lib/my_api_client/integrations/**/*'
    - 'spec/lib/my_api_client/errors/**/*'
    - 'spec/lib/my_api_client/rspec/**/*'

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 4
